document.writeln("     <!--Footer--> "); 
document.writeln("     <div class=\"footer\"> "); 
document.writeln("         <div class=\"container\"> "); 
document.writeln("             <div class=\"row\"> "); 
document.writeln("                 <div class=\"col-md-6 col-md-push-6 item text\"> "); 
document.writeln("                     <h3>CompuerShop Inc.</h3> "); 
document.writeln("                     <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p> "); 
document.writeln("                 </div> "); 
document.writeln("                 <div class=\"col-md-3 col-md-pull-6 col-sm-4 item\"> "); 
document.writeln("                     <h3>Services</h3> "); 
document.writeln("                     <ul> "); 
document.writeln("                         <li><a href=\"#\">Web design</a></li> "); 
document.writeln("                         <li><a href=\"#\">Development</a></li> "); 
document.writeln("                         <li><a href=\"#\">Hosting</a></li> "); 
document.writeln("                     </ul> "); 
document.writeln("                 </div> "); 
document.writeln("                 <div class=\"col-md-3 col-md-pull-6 col-sm-4 item\"> "); 
document.writeln("                     <h3>About</h3> "); 
document.writeln("                     <ul> "); 
document.writeln("                         <li><a href=\"#\">Company</a></li> "); 
document.writeln("                         <li><a href=\"#\">Team</a></li> "); 
document.writeln("                         <li><a href=\"#\">Careers</a></li> "); 
document.writeln("                     </ul> "); 
document.writeln("                 </div> "); 
document.writeln("                 <div class=\"col-md-12 col-sm-4 item social\"><a href=\"#\"><i class=\"fa fa-twitter-square\" style=\"font-size: 24px;\" aria-hidden=\"true\"></i></a> <a href=\"#\"><i class=\"fa fa-facebook-official\" style=\"font-size: 24px;\" aria-hidden=\"true\"></i></a> <a href=\"#\"><i class=\"fa fa-snapchat-square\" style=\"font-size: 24px;\" aria-hidden=\"true\"></i></a> <a href=\"#\"><i class=\"fa fa-instagram\" style=\"font-size: 24px;\" aria-hidden=\"true\"></i></a></div> "); 
document.writeln("             </div> ");
document.writeln("         </div> ");